<?php

function ap_custom_menu_alter(&$items){
    
    
}

function ap_custom_menu() {
  $items['user/%user/user-agreement'] = array(
    'title' => 'User Agreement', 
    'page callback' => 'drupal_goto', 
    'page arguments' => array('user-agreement'), 
    'access callback' => 'user_is_logged_in', 
    'type' => MENU_LOCAL_TASK,
    
  );

  return $items;
}

function accesspoint_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'user_profile_form') {
    unset($form['contact']);
  }
}

/**
* Implementation of hook_form_alter()
*/
function ap_custom_form_alter(&$form, &$form_state, $form_id) {

  switch ($form_id) {
    case 'webform_client_form_14630':
      $nid = $_GET['id'];
      $node = node_load($nid);
      // Add the node title to the webform field8
      $form['submitted']['hsa_carrier_to_be_quoted']['#default_value'] = $node->title;
      //}
      return $form;
    break;
  }
}
